services:
  db:
    image: postgres:16
    container_name: gm-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: gm-api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./schemas:/app/schemas
    command: >
      python -m uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: http://api:8000
    ports:
      - "3000:3000"

volumes:
  db_data:
